kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-client-provisioner
  namespace: opencloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-client-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      #      nodeSelector:
      #        node: meiweimin
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          #image: quay.io/external_storage/nfs-client-provisioner:latest    #在1.27版本中会出错
          image: gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner:v4.0.2
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: nfs
            - name: NFS_SERVER
              value: 192.168.2.2  # 替换为你的NFS服务器
            - name: NFS_PATH
              value: /opt/nfs/opencloud  # 替换为你的NFS文件夹
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.2.2  # 替换为你的NFS服务器
            path: /opt/nfs/opencloud  # 替换为你的NFS文件夹