apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
  namespace: opencloud
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"  # 是否设置为默认的storageclass
provisioner: nfs # or choose another name, must match deployment's env PROVISIONER_NAME'
allowVolumeExpansion: true
parameters:
  archiveOnDelete: "false"