apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: opencloud
  labels:
    app: redis
#Opaque 类型的数据是一个 map 类型，要求value是base64编码。
type: Opaque
data:
  redisPassword: VDk1TXc4WVlwSTV6N1Jzbw== #T95Mw8YYpI5z7Rso转成base64  echo -n "a123456!" | base64