apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: redis
  labels:
    app: redis
#Opaque 类型的数据是一个 map 类型，要求value是base64编码。
type: Opaque
data:
  redisPassword: eWtOSTR2T2JNc1AxNHlDNw== #123456转成base64  echo -n "a123456!" | base64