apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-master
  labels:
    app: mysql
    podindex: "0"
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  capacity:
    storage: "20Gi" # volume capacity
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "192.168.2.2" # hostname or IP address of the NFS server
    path: "/opt/k8s/shared/db/mysql/master" # mysql-replica-0 data directory path
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-slave
  labels:
    app: mysql
    podindex: "1"
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  capacity:
    storage: "20Gi" # volume capacity
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "192.168.2.2" # hostname or IP address of the NFS server
    path: "/opt/k8s/shared/db/mysql/slave" # mysql-replica-1 data directory path