# HEADLESS SERVICE
apiVersion: v1
kind: Service
metadata:
  name: percona-galera-xtradb
spec:
  clusterIP: None
  ports:
    - name: galera-replication
      port: 4567
      targetPort: 4567
    - name: state-transfer
      port: 4568
      targetPort: 4568
    - name: state-snapshot
      port: 4444
      targetPort: 4444
  selector:
    app: mysql
---
# SERVICIO CON BALANCEO
apiVersion: v1
kind: Service
metadata:
  name: mysql-db
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    app: mysql