#ServiceAccount是Kubernetes中的一种资源类型，用于定义容器中运行的进程的身份验证信息。它包含一个名称和一个由Kubernetes API服务器签发的Token，该Token用于对Kubernetes API进行身份验证和授权。
#ServiceAccount的主要用途是在Pod中运行的容器中自动提供身份验证信息。通过将ServiceAccount分配给Pod，容器可以使用该ServiceAccount的Token来与Kubernetes API进行交互。
#下面是一些ServiceAccount的具体使用场景：
#1. 用于Pod中的容器，以便它们可以与Kubernetes API进行交互。
#2. 用于在Pod中运行的应用程序，以便它们可以使用Kubernetes API进行自我管理。
#3. 用于授予Pod中的容器对其他Kubernetes资源（如Secrets和ConfigMaps）的访问权限。
apiVersion: v1                    #版本号
kind: ServiceAccount              #资源类型
metadata:                         #元数据
  name: my-service-account        #名称
  namespace: my-namespace         #命名空间
automountServiceAccountToken: false   #用于指定是否自动为Pod中的容器挂载ServiceAccount的Token。如果设置为 true ，则Pod中的所有容器都将自动挂载ServiceAccount的Token。如果设置为 false ，则不会自动挂载ServiceAccount的Token，容器需要手动挂载。
imagePullSecrets:                 #用于指定Pod中使用哪个Secret来拉取私有容器镜像。它允许您在不将Secret暴露给Pod的情况下使用私有容器镜像。
- name: docker-registry-secret
secrets:                          #用于指定哪些Secrets可以被此ServiceAccount的Token访问。它允许您控制哪些Secrets可以被Pod中的容器访问。
- name: sec-1
  namespace: opencloud