apiVersion: v1
kind: Service
metadata:
  name: mongodb-rs
  namespace: opencloud
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: mongo-pod-port
      nodePort: 30717
  selector:
    app: mongodb-rs
  type: NodePort