apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: opencloud
data:
  enabled_plugins: |
    [rabbitmq_management,rabbitmq_peer_discovery_k8s].
  #启用插件rabbitmq_management和rabbitmq_peer_discovery_k8s
  rabbitmq.conf: |
    cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.k8s.address_type = hostname
    #################################################
    # rabbit-mq is rabbitmq-cluster's namespace#
    #################################################
    cluster_formation.k8s.hostname_suffix = .rabbitmq.opencloud.svc.cluster.local
    cluster_formation.node_cleanup.interval = 30
    cluster_formation.node_cleanup.only_log_warning = true
    cluster_partition_handling = autoheal
    queue_master_locator=min-masters
    cluster_formation.randomized_startup_delay_range.max = 2
    vm_memory_high_watermark.absolute = 1GB
    disk_free_limit.absolute = 2GB
    loopback_users.guest = false
