apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: opencloud
  labels:
    app: redis
spec:
  ports:
    - name: client
      port: 6379
      targetPort: 6379
      protocol: TCP
      nodePort: 32222
  selector:
    app: redis
  type: NodePort